const catParser = {
  uncategorized: 'Other',
  searchenginesandportals: 'Search Engines',
  newsandmedia: 'News',
  streamingmedia: 'Streaming Media',
  entertainment: 'Entertainment',
  shopping: 'Shopping',
  vehicles: 'Vehicles',
  gambling: 'Gambling',
  informationtech: 'Technology',
  games: 'Games',
  sports: 'Sports',
  economyandfinance: 'Economy & Finance',
  jobrelated: 'Jobs & Career',
  hacking: 'Hacking',
  messageboardsandforums: 'Forums',
  socialnetworking: 'Social Media',
  chatandmessaging: 'Chat & Instant Messaging',
  mediasharing: 'Media Sharing',
  blogsandpersonal: 'Blogs',
  health: 'Health',
  adult: 'Adult Content',
  personals: 'Dating',
  religion: 'Religion',
  travel: 'Travel',
  abortion: 'Abortion',
  education: 'Education',
  drugs: 'Drugs',
  alcoholandtobacco: 'Alcohol & Tobbaco',
  business: 'Business',
  advertising: 'Advertising',
  humor: 'Humor',
  foodandrecipes: 'Food & Recipes',
  realestate: 'Real State',
  weapons: 'Weapons',
  proxyandfilteravoidance: 'Proxy & Filter Avoidance',
  virtualreality: 'Virtual Reality',
  translators: 'Translators',
  parked: 'Parked Sites',
  illegalcontent: 'Illegal Content',
  contentserver: 'Content Servers',
};

module.exports = catParser;